/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.webank.blockchain.hsm.crypto.sdf;

public class Key {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Key(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Key obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                SDFJNI.delete_Key(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public SWIGTYPE_p_unsigned_char PublicKey() {
        long cPtr = SDFJNI.Key_PublicKey(swigCPtr, this);
        return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    }

    public SWIGTYPE_p_unsigned_char PrivateKey() {
        long cPtr = SDFJNI.Key_PrivateKey(swigCPtr, this);
        return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    }

    public int PublicKeyLen() {
        return SDFJNI.Key_PublicKeyLen(swigCPtr, this);
    }

    public int PrivateKeyLen() {
        return SDFJNI.Key_PrivateKeyLen(swigCPtr, this);
    }

    public long Identifier() {
        return SDFJNI.Key_Identifier(swigCPtr, this);
    }

    public String Password() {
        return SDFJNI.Key_Password(swigCPtr, this);
    }

    public boolean IsInternalKey() {
        return SDFJNI.Key_IsInternalKey(swigCPtr, this);
    }

    public Key() {
        this(SDFJNI.new_Key__SWIG_0(), true);
    }

    public Key(
            SWIGTYPE_p_unsigned_char privateKey,
            int privateKeyLen,
            SWIGTYPE_p_unsigned_char publicKey,
            int publicKeyLen) {
        this(
                SDFJNI.new_Key__SWIG_1(
                        SWIGTYPE_p_unsigned_char.getCPtr(privateKey),
                        privateKeyLen,
                        SWIGTYPE_p_unsigned_char.getCPtr(publicKey),
                        publicKeyLen),
                true);
    }

    public Key(long keyIndex, String password) {
        this(SDFJNI.new_Key__SWIG_2(keyIndex, password), true);
    }

    public Key(long keyIndex) {
        this(SDFJNI.new_Key__SWIG_3(keyIndex), true);
    }

    public void setPrivateKey(SWIGTYPE_p_unsigned_char privateKey, long len) {
        SDFJNI.Key_setPrivateKey(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(privateKey), len);
    }

    public void setPublicKey(SWIGTYPE_p_unsigned_char publicKey, long len) {
        SDFJNI.Key_setPublicKey(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(publicKey), len);
    }
}
